### ISSUE TITLE
Support color scans

### ISSUE THREAD

**Issue by Biont** [e-alfred/nextcloud-scanner#1]
The app is currently hardcoded to do greyscale scans in a rather small resolution: https://github.com/e-alfred/nextcloud-scanner/blob/94a63c6522f04c6ea739bf2e5cafbedffcb77873/lib/Storage/ScannerStorage.php#L33

Do you think you could set this to do color scans by default? A greyscale image can easily be created from a color image, but not the other way around.

And the scan resolution could be a great thing to put in a configurable setting (if not an actual dialog with options)

**Comment by e-alfred** [comment]
It was implemented in this PR: https://github.com/e-alfred/nextcloud-scanner/pull/2

Maybe you can help test it?

**Comment by Biont** [comment]
Well it was working nicely when I submitted the PR :sweat_smile:
