### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by Failure404** [e-alfred/nextcloud-scanner#15]
Hi,
it used to work fine for me, but I haven't used it in a while. Today I am getting error messages using Nextcloud 16.0.3 and PHP 7.3.7:
`Undefined variable: result at /apps/scanner/controller/scannercontroller.php#64`
`Undefined variable: status at /apps/scanner/controller/scannercontroller.php#64`
`Undefined index: at /lib/private/AppFramework/Http.php#150`

**Comment by Biont** [comment]
Thanks for the report. We could definetely define those variables before going into the try/catch block, but I really don't see how it is possible for your error to occur.

**Comment by SmokeyBR** [comment]
i have the exact same errors first time using it thou.
php 7.2.19-0ubuntu0.18.04.2 and  Nextcloud 16.0.4

if you got any ideas of what i can do for more indo id be happy to do it.

**Comment by SmokeyBR** [comment]
guys i dont think its a bug it was missing user www-data being added to the sudoers file.
thats my bad since README does warn you about it, i just edited the sudoers wrong and it broke.

**Comment by v-sim** [comment]
work after insert into controller/scannercontroller.php

```
        public function scan($filename, $dir, $scanOptions) {
+                $status = Http::STATUS_OK; $result = 'result';
                $path = $dir . '/' . $filename;
                $mode = (int)$scanOptions['mode'];
                $resolution = (int)$scanOptions['resolution'];

```

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/nextcloud-scanner/pull/18.
