### ISSUE TITLE
scanimage support jpeg natively

### ISSUE THREAD

**Issue by v-sim** [e-alfred/nextcloud-scanner#16]
in apps/scanner/lib/Storage/ScannerStorage.php replace

```
diff --git a/lib/Storage/ScannerStorage.php b/lib/Storage/ScannerStorage.php
index 868b6e0..6871c84 100644
--- a/lib/Storage/ScannerStorage.php
+++ b/lib/Storage/ScannerStorage.php
@@ -57,7 +57,7 @@ class ScannerStorage {
                $file = $this->storage->newFile($name);
                // TODO: There's probably a way to stream this without the tempfile
                exec(
-                       "sudo scanimage --mode {$this->modes[$mode]} --resolution {$resolution} -x 215 -y 297| pnmtojpeg > /tmp/im
g",
+                        "scanimage --format=jpeg --mode {$this->modes[$mode]} --resolution {$resolution} > /tmp/img",
                        $output,
                        $status
                );

```

**Comment by e-alfred** [comment]
Thanks for your support, can you create Pull Requests for your improvements so it can be merged directly into the repository?

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/nextcloud-scanner/pull/17.

**Comment by e-alfred** [comment]
@v-sim Sadly while this would be an improvement and a reduction on dependencies, it causes serious problems with certain backends (image size too small, rotation not correct, cut off image). For now I reverted back to the old processing method, if you have a good idea on how to solve these problems it would be highly appreciated!
