### ISSUE TITLE
Printer-App based on this one here?

### ISSUE THREAD

**Issue by Schmuuu** [e-alfred/nextcloud-scanner#3]
Hello, 

I'm sorry for misusing this repository here, I just didn't find any other way to contact the owner e-alfred.
I really like the idea of this app and will implement it on my home server soon. And now I'm wondering if you could build an app nextcloud-printer as well? While you are the first developer I saw so far who is developing an app integrating the home devices, I thought I just ask.

Just like scanning papers and directly storing them on the server, I would love to print files from the server directly to the printer in my home network.
Right now I need to download the relevant file, open it on the computer and print it. If I'm somewhere without a printer, I can't do that at that moment.
A printer app would be awesome. Without the need to download the file, we could directly print it and you can start printing from anywhere :)
Let's say you need a document of 100 pages printed. You trigger the printing on the web GUI, drive home and have the document directly available in your printer's output tray :) grab it, reach the post office in time before the end of business hours and successfully send your papers on the same day. 

I hope this is an idea you like and that there will be such a project in your repository soon :D

**Comment by e-alfred** [comment]
I am not sure completely about it yet, but it might be possible. Maybe printing could be done by selecting a file (or more) and then add a printer button sending the files to a CUPS server. There is a PHP library with CUPS IPP support here: https://github.com/smalot/cups-ipp

**Comment by e-alfred** [comment]
Good news!

I made an app that allows direct printing from Nextcloud through a CUPS-connected printer. It is not based on this app, but partly on the Checksum app. Also, it is very very basic at the moment, so not all features are available currently.

Here is the repository: https://github.com/e-alfred/nextcloud-printer
