### ISSUE TITLE
Nextcloud v25 knocking at the doors (pls make app compatible to NC25)

### ISSUE THREAD

**Issue by JimmyKater** [e-alfred/nextcloud-scanner#37]
after compability to NC24 seems to be reached (https://github.com/e-alfred/nextcloud-scanner/pull/35 ) but not merged, yet it appears to be mandatory to make this app compatible with NC 25 which is going to be released pretty soon (right now they are testdriving RC3 or RC4 of NC25)

Thanks in advance to everyone involved

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by e-alfred** [comment]
Fixed by releasing Version 0.2.3.
