### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by Biont** [e-alfred/nextcloud-scanner#4]
Hello.

Nextcloud 15 has just been released and this app is not compatible with it. I'm sure this is just a matter of formally declaring support. Can you please create a new release so we can keep using the app with NC15?

**Comment by e-alfred** [comment]
Sorry for the delay, I will publish a new version to the App Store soon. The app should work well if you increase the `max-version` in `appinfo/info.xml`.

**Comment by e-alfred** [comment]
@Biont Do you mind if you could add two more fields so users can easily set the size of the scan? Currently it is hardcoded to A4 using the X and Y parameters (which should be default because most scanners have that size) but if users want to scan a different size it would be great to have that possibility.

**Comment by Biont** [comment]
@e-alfred I have seen that commit and have already been thinking about doing this. Thing is: a _fast_ solution would be to provide those 2 fields just so that there is *some* user-facing way to change those params.
 An _awesome_ solution would be to mimick actual scanning applications and let the users draw a rectangle over a preview of the scan.

This of course needs a LOT more work. I'm willing to do it, but I cannot do it quickly.

Is this blocking a new release in your opinion?

**Comment by e-alfred** [comment]
No, for now it should be okay. This app is WIP anyway, so this feature could be implemented later on. A field to select the scan size would be great (maybe even from a preview scan), at the interim two simple fields for X and Y axis (defaulting to 210 and 297 respectively) should be good enough.

I published a new version to the Nextcloud App Store, so I will close this issue and create a few more for upcoming features.
