### ISSUE TITLE
i18n & l10n

### ISSUE THREAD

**Issue by Biont** [e-alfred/nextcloud-scanner#9]
There are only hardcoded English strings throughout the code. We should make the app translateable at some point

**Comment by e-alfred** [comment]
I added some initial support for translation in this commit: https://github.com/e-alfred/nextcloud-scanner/commit/319086d2654092f45d928047cfe6bcf8be7af592

Currently the only problem is the optionsdialog.html file where translation doesn't work correctly at the moment.

**Comment by e-alfred** [comment]
Fixed finally by https://github.com/e-alfred/nextcloud-scanner/commit/97dbab823f04eb78bab70a44d2ab34def23f741f.
